- name: Removing Strimzi cluster nodes
  k8s_v1_config_map:
    name: my-cluster
    namespace: "{{ namespace}}"
    state: absent
 
# Check for deprovision tasks from the cluster operator
- name: "Wait on deprovision tasks from the cluster operator"
  shell: oc get pods --namespace={{ namespace }} | grep my-cluster | wc -l
  register: cluster_result
  until: cluster_result.stdout.find("0") != -1
  retries: 30
  delay: 5

- name: Removing Strimzi Operator
  k8s_extensions_v1beta1_deployment:
    name: strimzi-cluster-controller
    namespace: "{{ namespace}}"
    state: absent
